import Head from 'next/head'
import Link from 'next/link';
import Chapter from '../../components/Chapters/Chapter';
import Tag from '../../components/Tag/Tag';
import { getAllPosts, getAllTags, getPostsTopPage } from '../../lib/notionAPI';

export const getStaticProps = async () => {
  const slicePosts = await getPostsTopPage(1);
  const allTags = await getAllTags();

  return {
    props: {
      slicePosts,
      allTags
    },
    revalidate: 60 * 60 * 12,
  }
}

export default function Home({ slicePosts, allTags }) {
  return (
    <>
      <Head>
        <title>VueCurriculum-Expert</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='container'>
        <h1 className='common_pageTitle'>VueCurriculum-Expert</h1>
        {slicePosts.map((post) => (
          <div key={post.id}>
            <Chapter
              title={post.title}
              description={post.description}
              date={post.date}
              tags={post.tags}
              slug={post.slug}
              isPaginationPage={false}
            />
          </div>
        ))}
        <div className='link_wrapper'>
          <Link href="/posts/page/1" className='curriculum-page_link'>カリキュラム一覧ページ</Link>
        </div>
        <Tag tags={allTags} />
      </main>
    </>
  )
}
